In [3]:
import mysql.connector
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine, Column, String, Float, DateTime, Integer
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import declarative_base

In [4]:
# Configurar la conexión a la base de datos
user = "root"
password = "12345678"
host = "localhost"
database = "cripto_db"

engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}/{database}")

In [6]:
df = pd.read_csv('..\Dataset\historial_rendimiento_bonos_tesoro.csv')

In [35]:
# Cambiar los nombres de las columnas
df.rename(columns={'Date': 'fecha', 'Open': 'open','High': 'high','Low': 'low','Close': 'close'}, inplace=True)

In [36]:
df.head(10)

        fecha   open   high    low  close  Adj Close  Volume
0  2018-01-02  2.433  2.480  2.425  2.465      2.465       0
1  2018-01-03  2.451  2.465  2.440  2.447      2.447       0
2  2018-01-04  2.473  2.487  2.449  2.453      2.453       0
3  2018-01-05  2.465  2.480  2.436  2.476      2.476       0
4  2018-01-08  2.471  2.489  2.462  2.480      2.480       0
5  2018-01-09  2.491  2.546  2.489  2.546      2.546       0
6  2018-01-10  2.584  2.595  2.550  2.550      2.550       0
7  2018-01-11  2.564  2.570  2.526  2.531      2.531       0
8  2018-01-12  2.548  2.594  2.546  2.552      2.552       0
9  2018-01-16  2.539  2.563  2.526  2.544      2.544       0

In [37]:
# Crear una sesión
Session = sessionmaker(bind=engine)
session = Session()

# Definir la clase modelo
Base = declarative_base()

class BonosUSA(Base):
    __tablename__ = 'bonos_usa'

    id = Column(Integer, primary_key=True)
    fecha = Column(DateTime)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)

# Leer los datos desde un DataFrame
df_bonos = pd.DataFrame(df)
df_bonos['fecha'] = pd.to_datetime(df_bonos['fecha'])

# Agregar los datos a la base de datos
for index, row in df.iterrows():
    bonos_entry = BonosUSA(
        fecha=row['fecha'],
        open=row['open'],
        high=row['high'],
        low=row['low'],
        close=row['close']
    )
    session.add(bonos_entry)

# Confirmar los cambios y cerrar la sesión
session.commit()
session.close()

print("Datos importados a la tabla 'bonos_usa' ")

Datos importados a la tabla 'bonos_usa'